// 
// DO NOT EDIT THIS FILE MANUALLY 
// 
// This file is automatically generated in the pre-build step by the UpdateVersion.bat script 
// Change the version number in the ZipComponentUWP.rc file 
// 
// DO NOT EDIT THIS FILE MANUALLY  
//  
#include "pch.h" 
#include <cvt/wstring> 
#include <codecvt> 
#include "ZipAlgorithm.h" 
#include "ZipComponent.h" 
 
using namespace ZipComponentUWP; 
 
String^ ZipComponent::GetVersion() 
{ 
	return "1.0.2.0"; 
} 
